[workspace]
resolver = "3"
members = [
    "crates/okuri-core",
    "crates/okuri-providers",
    "crates/okuri-engine",
    "crates/okuri",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/monorkin/okuri"

[workspace.dependencies]
okuri-core = { path = "crates/okuri-core" }
okuri-engine = { path = "crates/okuri-engine" }
okuri-providers = { path = "crates/okuri-providers" }

async-trait = "0.1"
bytes = "1"
futures = "0.3"
thiserror = "2"
time = "0.3"
tokio = "1"
